{
 "title": "Acronymbot",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Network bytes received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 19, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\"k8s_POD_acronymbot-deployment-.*\"}[5m])) by (name)"
    }
   ]
  },
  {
   "title": "num of pods",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas{deployment=\"acronymbot-deployment\"})"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(container_memory_usage_bytes{container_name=\"acronymbot\", namespace=\"marcelo\"})"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(\n  rate(container_cpu_usage_seconds_total{namespace=~\"marcelo\", container_name=\"acronymbot\",container_name!=\"\", container_name!=\"POD\"}[5m])\n  )by (container_name)"
    }
   ]
  },
  {
   "title": "pod count",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(kube_deployment_status_replicas_available{deployment=\"acronymbot-deployment\"})"
    }
   ]
  }
 ]
}