name: Hello Testing
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build-and-run:
    name: Build and Run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Echo
        run: echo "meh meh test"
